handler: deregister-sub.handler
name: ${self:service.name}
layers:
  - { Ref: LayerLambdaLayer }
package:
  include:
    - 'lambda/deregister-sub/deregister-sub.js'
    - 'lambda/deregister-sub/helpers/**'
environment:
  ES_ID: ${env:ES_ID}
  ES_SECRET: ${env:ES_SECRET}
  ES_ENDPOINT: ${env:ES_ENDPOINT}
events:
  - eventBridge:
      eventBus: ${env:EVENT_BUS_ARN}
      pattern:
        detail:
          responsePayload:
            hasDeadEndpoints:
              - true
